apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: cluster-fileintegrity
  namespace: openshift-file-integrity
spec:
#  nodeSelector:
#      node-role.kubernetes.io/worker: ""
  config: {}